services:
  nginx:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./static:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    user: nginxuser  
    restart: unless-stopped
